<a href="https://colab.research.google.com/github/saravananmaran/Development-of-a-Healthcare-Operations-Intelligence-Dashboard-with-Decision-Analytics/blob/main/SQL_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Interview Practice — 20 Questions with Answers

Google Colab-ready SQL interview workbook.

**Database:** SQLite  
**Level:** Easy → Medium  
**Topics:** SELECT, WHERE, DISTINCT, GROUP BY, HAVING, JOIN, subquery, self join, window functions, dates.

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")
c = conn.cursor()

c.execute('''
CREATE TABLE Employees (
    EmpID INTEGER PRIMARY KEY,
    EmpName TEXT NOT NULL,
    DepartmentID INTEGER,
    ManagerID INTEGER,
    Salary INTEGER,
    HireDate DATE,
    City TEXT
);
''')

c.execute('''
CREATE TABLE Departments (
    DepartmentID INTEGER PRIMARY KEY,
    DepartmentName TEXT NOT NULL
);
''')

employees = [
    (1, 'Alice', 101, None, 60000, '2021-01-10', 'Chennai'),
    (2, 'Bob', 102, 4, 80000, '2022-03-15', 'Bangalore'),
    (3, 'Charlie', 101, 1, 65000, '2023-06-20', 'Chennai'),
    (4, 'David', 102, None, 90000, '2020-08-12', 'Bangalore'),
    (5, 'Eve', 101, 1, 70000, '2022-09-01', 'Chennai'),
    (6, 'Frank', 103, None, 75000, '2024-01-18', 'Mumbai')
]

departments = [
    (101, 'HR'),
    (102, 'Engineering'),
    (103, 'Marketing'),
    (104, 'Finance')
]

c.executemany("INSERT INTO Employees VALUES (?, ?, ?, ?, ?, ?, ?)", employees)
c.executemany("INSERT INTO Departments VALUES (?, ?)", departments)
conn.commit()

def run_sql_query(query):
    return pd.read_sql_query(query, conn)

print("Database ready!")

Database ready!

## 1. Select all employees

**Interview Answer:**

In [2]:
query = """
SELECT * FROM Employees;
"""

display(run_sql_query(query))

   EmpID  EmpName  DepartmentID  ManagerID  Salary    HireDate       City
0      1    Alice           101        NaN   60000  2021-01-10    Chennai
1      2      Bob           102        4.0   80000  2022-03-15  Bangalore
2      3  Charlie           101        1.0   65000  2023-06-20    Chennai
3      4    David           102        NaN   90000  2020-08-12  Bangalore
4      5      Eve           101        1.0   70000  2022-09-01    Chennai
5      6    Frank           103        NaN   75000  2024-01-18     Mumbai

**Explanation:** `SELECT *` returns all columns and rows.

## 2. Select employee name and salary

**Interview Answer:**

In [3]:
query = """
SELECT EmpName, Salary FROM Employees;
"""

display(run_sql_query(query))

   EmpName  Salary
0    Alice   60000
1      Bob   80000
2  Charlie   65000
3    David   90000
4      Eve   70000
5    Frank   75000

**Explanation:** Select only the required columns.

## 3. Employees earning more than 70,000

**Interview Answer:**

In [4]:
query = """
SELECT * FROM Employees WHERE Salary > 70000;
"""

display(run_sql_query(query))

   EmpID EmpName  DepartmentID  ManagerID  Salary    HireDate       City
0      2     Bob           102        4.0   80000  2022-03-15  Bangalore
1      4   David           102        NaN   90000  2020-08-12  Bangalore
2      6   Frank           103        NaN   75000  2024-01-18     Mumbai

**Explanation:** `WHERE` filters rows based on a condition.

## 4. Sort employees by salary descending

**Interview Answer:**

In [5]:
query = """
SELECT * FROM Employees ORDER BY Salary DESC;
"""

display(run_sql_query(query))

   EmpID  EmpName  DepartmentID  ManagerID  Salary    HireDate       City
0      4    David           102        NaN   90000  2020-08-12  Bangalore
1      2      Bob           102        4.0   80000  2022-03-15  Bangalore
2      6    Frank           103        NaN   75000  2024-01-18     Mumbai
3      5      Eve           101        1.0   70000  2022-09-01    Chennai
4      3  Charlie           101        1.0   65000  2023-06-20    Chennai
5      1    Alice           101        NaN   60000  2021-01-10    Chennai

**Explanation:** `ORDER BY ... DESC` sorts from highest to lowest.

## 5. Find unique department IDs

**Interview Answer:**

In [6]:
query = """
SELECT DISTINCT DepartmentID FROM Employees;
"""

display(run_sql_query(query))

   DepartmentID
0           101
1           102
2           103

**Explanation:** `DISTINCT` removes duplicate values.

## 6. Count total employees

**Interview Answer:**

In [7]:
query = """
SELECT COUNT(*) AS TotalEmployees FROM Employees;
"""

display(run_sql_query(query))

   TotalEmployees
0               6

**Explanation:** `COUNT(*)` counts all rows.

## 7. Total salary by department

**Interview Answer:**

In [8]:
query = """
SELECT DepartmentID, SUM(Salary) AS TotalSalary FROM Employees GROUP BY DepartmentID;
"""

display(run_sql_query(query))

   DepartmentID  TotalSalary
0           101       195000
1           102       170000
2           103        75000

**Explanation:** `GROUP BY` creates department groups and `SUM` totals their salaries.

## 8. Departments with total salary above 150,000

**Interview Answer:**

In [9]:
query = """
SELECT DepartmentID, SUM(Salary) AS TotalSalary FROM Employees GROUP BY DepartmentID HAVING SUM(Salary) > 150000;
"""

display(run_sql_query(query))

   DepartmentID  TotalSalary
0           101       195000
1           102       170000

**Explanation:** `HAVING` filters aggregated groups.

## 9. Employees with department names

**Interview Answer:**

In [10]:
query = """
SELECT E.EmpName, D.DepartmentName FROM Employees E INNER JOIN Departments D ON E.DepartmentID = D.DepartmentID;
"""

display(run_sql_query(query))

   EmpName DepartmentName
0    Alice             HR
1      Bob    Engineering
2  Charlie             HR
3    David    Engineering
4      Eve             HR
5    Frank      Marketing

**Explanation:** `INNER JOIN` combines matching employee and department rows.

## 10. Employees above average salary

**Interview Answer:**

In [11]:
query = """
SELECT EmpName, Salary FROM Employees WHERE Salary > (SELECT AVG(Salary) FROM Employees);
"""

display(run_sql_query(query))

  EmpName  Salary
0     Bob   80000
1   David   90000
2   Frank   75000

**Explanation:** The subquery calculates the overall average first.

## 11. Highest salary

**Interview Answer:**

In [12]:
query = """
SELECT MAX(Salary) AS HighestSalary FROM Employees;
"""

display(run_sql_query(query))

   HighestSalary
0          90000

**Explanation:** `MAX` returns the largest salary.

## 12. Second-highest distinct salary

**Interview Answer:**

In [13]:
query = """
SELECT MAX(Salary) AS SecondHighestSalary FROM Employees WHERE Salary < (SELECT MAX(Salary) FROM Employees);
"""

display(run_sql_query(query))

   SecondHighestSalary
0                80000

**Explanation:** Find the maximum salary below the overall maximum.

## 13. Employees with highest salary

**Interview Answer:**

In [14]:
query = """
SELECT EmpName, Salary FROM Employees WHERE Salary = (SELECT MAX(Salary) FROM Employees);
"""

display(run_sql_query(query))

  EmpName  Salary
0   David   90000

**Explanation:** Returns all employees tied at the highest salary.

## 14. Highest-paid employee in each department

**Interview Answer:**

In [15]:
query = """
SELECT EmpName, DepartmentID, Salary
FROM (
    SELECT EmpName, DepartmentID, Salary,
           ROW_NUMBER() OVER (
               PARTITION BY DepartmentID
               ORDER BY Salary DESC
           ) AS rn
    FROM Employees
) x
WHERE rn = 1;
"""

display(run_sql_query(query))

  EmpName  DepartmentID  Salary
0     Eve           101   70000
1   David           102   90000
2   Frank           103   75000

**Explanation:** `PARTITION BY` ranks employees separately inside each department.

## 15. Rank all employees by salary

**Interview Answer:**

In [16]:
query = """
SELECT EmpName, Salary,
       RANK() OVER (ORDER BY Salary DESC) AS SalaryRank
FROM Employees;
"""

display(run_sql_query(query))

   EmpName  Salary  SalaryRank
0    David   90000           1
1      Bob   80000           2
2    Frank   75000           3
3      Eve   70000           4
4  Charlie   65000           5
5    Alice   60000           6

**Explanation:** `RANK` assigns the same rank to tied salaries.

## 16. Employees earning more than their manager

**Interview Answer:**

In [17]:
query = """
SELECT E.EmpName AS Employee,
       E.Salary AS EmployeeSalary,
       M.EmpName AS Manager,
       M.Salary AS ManagerSalary
FROM Employees E
JOIN Employees M ON E.ManagerID = M.EmpID
WHERE E.Salary > M.Salary;
"""

display(run_sql_query(query))

  Employee  EmployeeSalary Manager  ManagerSalary
0  Charlie           65000   Alice          60000
1      Eve           70000   Alice          60000

**Explanation:** A self join lets us compare an employee row with the manager row.

## 17. Departments with no employees

**Interview Answer:**

In [18]:
query = """
SELECT D.DepartmentID, D.DepartmentName
FROM Departments D
LEFT JOIN Employees E
ON D.DepartmentID = E.DepartmentID
WHERE E.EmpID IS NULL;
"""

display(run_sql_query(query))

   DepartmentID DepartmentName
0           104        Finance

**Explanation:** `LEFT JOIN` keeps every department; NULL identifies unmatched departments.

## 18. Average salary by department

**Interview Answer:**

In [19]:
query = """
SELECT DepartmentID,
       ROUND(AVG(Salary), 2) AS AverageSalary
FROM Employees
GROUP BY DepartmentID;
"""

display(run_sql_query(query))

   DepartmentID  AverageSalary
0           101        65000.0
1           102        85000.0
2           103        75000.0

**Explanation:** `AVG` calculates the mean salary for each department.

## 19. Top 2 employees in each department

**Interview Answer:**

In [20]:
query = """
SELECT EmpName, DepartmentID, Salary
FROM (
    SELECT EmpName, DepartmentID, Salary,
           DENSE_RANK() OVER (
               PARTITION BY DepartmentID
               ORDER BY Salary DESC
           ) AS rnk
    FROM Employees
) x
WHERE rnk <= 2
ORDER BY DepartmentID, Salary DESC;
"""

display(run_sql_query(query))

   EmpName  DepartmentID  Salary
0      Eve           101   70000
1  Charlie           101   65000
2    David           102   90000
3      Bob           102   80000
4    Frank           103   75000

**Explanation:** `DENSE_RANK` ranks salaries within each department and handles ties.

## 20. Employees hired from 2023 onward

**Interview Answer:**

In [21]:
query = """
SELECT EmpName, HireDate
FROM Employees
WHERE HireDate >= '2023-01-01'
ORDER BY HireDate;
"""

display(run_sql_query(query))

   EmpName    HireDate
0  Charlie  2023-06-20
1    Frank  2024-01-18

**Explanation:** The date condition returns employees hired on or after 1 January 2023.

In [22]:
conn.close()
print("Database connection closed.")

Database connection closed.